apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2-pv
  namespace: project
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.158.11
    path: /nfs/db2
